version: "3.8"
services:
  rhjoerg-maven-repository:
    image: rhjoerg/rhjoerg-maven-repository-standalone
    volumes:
        - type: bind
          source: ~/rhjoerg-maven-repository
          target: /data
    ports:
        - 8000:80
